name: PR targeting Main

on:
  workflow_dispatch:
  pull_request:
    branches: main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    uses: ./.github/workflows/_run-tests.yaml
